# Generated by Django 4.2.9 on 2024-06-12 23:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('visivel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('about', models.TextField(max_length=200, verbose_name='Resumo')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Data da publicação')),
                ('featured_image', models.ImageField(upload_to='blog_featured_images/', verbose_name='Imagem de Destaque')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Post: ')),
                ('destaque_home', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=255, unique=True)),
                ('img_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição da Imagem')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/', verbose_name='Imagem')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('about', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensagem', models.TextField(max_length=500, verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False)),
                ('status', models.BooleanField(choices=[(True, 'Respondida'), (False, 'Não Respondida')], default=False, max_length=30)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='depoimentos/')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Depoimento: ')),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='depoimentos/backgrounds/')),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.blogpost')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.category', verbose_name='Categoria'),
        ),
    ]
