# Generated by Django 4.2.9 on 2024-02-07 01:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='about',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(verbose_name='Data da publicação'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
    ]
