# Generated by Django 4.2.9 on 2024-02-07 02:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_blogpost_about_alter_blogpost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='about',
            field=models.TextField(max_length=150, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
