# Generated by Django 4.2.9 on 2024-02-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_carouselimage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155, verbose_name='nome')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('mensagem', models.TextField(blank=True, max_length=500, null=True, verbose_name='mensagem')),
                ('status', models.BooleanField(choices=[(True, 'Respondida'), (False, 'Não Respondida')], default=False, max_length=30)),
            ],
        ),
    ]
