# Generated by Django 4.2.9 on 2024-02-07 16:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_blogpost_about_alter_blogpost_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Texto : '),
        ),
    ]
