# Generated by Django 4.2.9 on 2024-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_inscricao_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
