# Generated by Django 4.2.9 on 2024-02-08 13:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_blogpost_about_alter_blogpost_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Texto : '),
        ),
    ]
