# Generated by Django 4.2.9 on 2024-02-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='telefone'),
        ),
    ]
