# Generated by Django 4.2.9 on 2024-02-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_category_about_alter_blogpost_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
