# Generated by Django 4.2.9 on 2024-02-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_inscricao_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
