# Generated by Django 4.2.9 on 2024-02-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_inscricao_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='visivel',
            field=models.BooleanField(default=False),
        ),
    ]
