# Generated by Django 4.2.9 on 2024-02-07 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_contato_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
