# Generated by Django 4.2.9 on 2024-02-08 16:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_contato_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Post: '),
        ),
    ]
