# Generated by Django 4.2.9 on 2024-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_contato_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link do Banner'),
        ),
    ]
