# Generated by Django 4.2.9 on 2024-02-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_blogpost_text'),
        ('administration', '0007_alter_carouselimage_options_carouselimage_link'),
    ]

    operations = [
    ]
