# Generated by Django 4.2.9 on 2024-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_merge_20240208_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
