# Generated by Django 4.2.9 on 2024-03-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img_description',
            field=models.CharField(blank=True, null=True, verbose_name='Descrição da Imagem'),
        ),
    ]
