# Generated by Django 4.2.9 on 2024-02-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_carouselimage_link_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='about',
            field=models.TextField(max_length=200, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
