# Generated by Django 4.2.7 on 2024-02-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_blogpost_about_alter_carouselimage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
