# Generated by Django 4.2.9 on 2024-02-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_blogpost_text'),
        ('administration', '0010_alter_blogpost_about_alter_carouselimage_link'),
    ]

    operations = [
    ]
