# Generated by Django 4.2.9 on 2024-03-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_blogpost_img_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='image_descriptions',
            field=models.CharField(blank=True, null=True, verbose_name='Descrição da imagem'),
        ),
    ]
