# Generated by Django 4.2.7 on 2024-02-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_contato_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='status',
            field=models.BooleanField(choices=[(True, 'Respondida'), (False, 'Não Respondida')], default=False, max_length=30),
        ),
    ]
