# Generated by Django 4.2.9 on 2024-03-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_carouselimage_image_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image_descriptions',
        ),
    ]
