# Generated by Django 4.2.9 on 2024-02-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_alter_blogpost_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='description',
        ),
    ]
