# Generated by Django 4.2.9 on 2024-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_alter_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
