# Generated by Django 4.2.9 on 2024-02-09 14:58

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_alter_category_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='depoimentos/')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('depoimento', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Depoimento: ')),
            ],
        ),
    ]
