# Generated by Django 4.2.9 on 2024-02-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_depoimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depoimento',
            old_name='depoimento',
            new_name='descricao',
        ),
    ]
