# Generated by Django 4.2.9 on 2024-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_rename_depoimento_depoimento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='depoimentos/backgrounds/'),
        ),
    ]
