# Generated by Django 4.2.9 on 2024-02-12 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_depoimento_imagem_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
