# Generated by Django 4.2.9 on 2024-02-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_carouselimage_ativo_carouselimage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
