# Generated by Django 4.2.9 on 2024-02-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_carouselimage_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
