# Generated by Django 4.2.9 on 2024-02-13 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_depoimento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
