# Generated by Django 4.2.9 on 2024-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_depoimento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='destaque_home',
            field=models.BooleanField(default=True),
        ),
    ]
