# Generated by Django 4.2.9 on 2024-02-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_merge_20240213_0944'),
        ('administration', '0024_blogpost_destaque_home'),
    ]

    operations = [
    ]
